# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "editify-dev"
client_id = "8198bc4d24cec22808ae47b0504bc324"
application_url = "https://drum-satisfaction-mess-regard.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders, read_customers, write_customers, write_orders, read_products, write_order_edits"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://drum-satisfaction-mess-regard.trycloudflare.com/auth/callback",
  "https://drum-satisfaction-mess-regard.trycloudflare.com/auth/shopify/callback",
  "https://drum-satisfaction-mess-regard.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-04"

[pos]
embedded = false

[app_preferences]
url = "https://editify-dev-91eba309cd61.herokuapp.com/"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "albertogaucin.myshopify.com"
