# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders, read_customers, write_customers, write_orders, read_products, write_order_edits, write_draft_orders, write_content, read_content, read_script_tags, write_script_tags"
